TEXTS = {
    'uz': {
        'welcome': "👋 Xush kelibsiz! Oltin (XAU/USD) signallari botiga xush kelibsiz.\n\nPastdagi tugmalar orqali botni boshqaring:",
        'tariffs_btn': "📊 Tariflar",
        'profile_btn': "👤 Profilim",
        'status_btn': "📈 Bozor Holati",
        'news_btn': "🗞 Yangiliklar",
        'settings_btn': "⚙️ Sozlamalar",
        'signal_btn': "✍️ Signal Yozish",
        'choose_tariff': "💎 <b>Premium Tariflar</b>\n\nTarifni tanlang:",
        'week_10': "🗓 1 Hafta - $10",
        'month_30': "📅 1 Oy - $30",
        'back': "🔙 Orqaga",
        'profile_active': "✅ Faol",
        'profile_inactive': "❌ Faol emas",
        'profile_info': "👤 <b>Profil</b>\n\nID: <code>{user_id}</code>\nObuna: {status}\nTugash vaqti: {expiry}",
        'market_status': "📊 <b>GOLD (XAU/USD) HOLATI</b>\n\nAktiv: <b>GOLD</b>\nNarx: <b>{price:.2f}</b>\nVaqt: <code>{time}</code>",
        'news_header': "📅 <b>Iqtisodiy Kalendar (USD)</b>\n\n",
        'no_news': "📅 <b>Iqtisodiy Kalendar</b>\n\nYaqin 24 soat ichida muhim yangiliklar yo'q.",
        'settings_menu': "⚙️ <b>Sozlamalar</b>\n\nTilni tanlang yoki yordam oling:",
        'lang_uz': "🇺🇿 O'zbekcha",
        'lang_ru': "🇷🇺 Русский",
        'help_btn': "ℹ️ Yordam",
        'help_text': "ℹ️ <b>Yordam Markazi</b>\n\nBotdan foydalanish bo'yicha qo'llanma:\n\n1. 📊 <b>Tariflar</b> - Premium obuna sotib olish.\n2. 📈 <b>Bozor Holati</b> - Ayni vaqtdagi narx navo.\n3. 🗞 <b>Yangiliklar</b> - Muhim iqtisodiy yangiliklar.\n4. ⚙️ <b>Sozlamalar</b> - Tilni o'zgartirish.\n\nAgar savollaringiz bo'lsa admin bilan bog'laning: @musoqudratov",
        'lang_changed': "✅ Til o'zgartirildi: O'zbekcha",
        'payment_info': "💳 <b>To'lov Ma'lumotlari</b>\n\nTarif: <b>{duration}</b>\nNarxi: <b>{price}</b>\n\nTo'lov uchun USDT (TRC20) manzili:\n<code>TYourActualUsdtAddressHere</code>\n\n⚠️ <b>Muhim:</b> To'lov qilganingizdan so'ng, skrinshotni @musoqudratov ga yuboring.",
        'sub_approved': "🎉 <b>Premium Faollashtirildi!</b>\nKunlar: {days}\nTugash vaqti: {date}\n\nKanal: <a href='{link}'>Kirish</a>",
        'sub_rejected': "❌ To'lov so'rovingiz rad etildi.",
        'cancel': "Bekor qilish",
        'cancelled': "❌ Bekor qilindi.",
        'back_to_main': "Pastdagi tugmalar orqali botni boshqaring:",
        'manual_signal_start': "📝 <b>Yangi Signal Yaratish</b>\n\nSignal turini tanlang:",
        'manual_signal_price': "✅ {type} tanlandi.\n\nEndi <b>Kirish Narxini</b> yuboring (masalan: 2030.50):",
        'manual_signal_sl': "✅ Narx: {price}\n\nEndi <b>Stop Loss (SL)</b> narxini yuboring:",
        'manual_signal_tp': "✅ SL: {sl}\n\nEndi <b>Take Profit (TP)</b> narxini yuboring:",
        'manual_signal_reason': "✅ TP: {tp}\n\nEndi <b>Signal Sababini</b> yozing (masalan: Trendline Support):",
        'manual_signal_preview': "✅ Signal tayyorlandi! Quyida ko'rib chiqing:",
        'error_num': "⚠️ Iltimos, faqat raqam yuboring.",
        'error_type': "⚠️ Iltimos, BUY yoki SELL ni tanlang."
    },
    'ru': {
        'welcome': "👋 Добро пожаловать! Бот торговых сигналов по золоту (XAU/USD).\n\nУправляйте ботом с помощью кнопок ниже:",
        'tariffs_btn': "📊 Тарифы",
        'profile_btn': "👤 Профиль",
        'status_btn': "📈 Рынок",
        'news_btn': "🗞 Новости",
        'settings_btn': "⚙️ Настройки",
        'signal_btn': "✍️ Сигнал",
        'choose_tariff': "💎 <b>Премиум Тарифы</b>\n\nВыберите тариф:",
        'week_10': "🗓 1 Неделя - $10",
        'month_30': "📅 1 Месяц - $30",
        'back': "🔙 Назад",
        'profile_active': "✅ Активен",
        'profile_inactive': "❌ Не активен",
        'profile_info': "👤 <b>Профиль</b>\n\nID: <code>{user_id}</code>\nПодписка: {status}\nИстекает: {expiry}",
        'market_status': "📊 <b>GOLD (XAU/USD) СТАТУС</b>\n\nАктив: <b>GOLD</b>\nЦена: <b>{price:.2f}</b>\nВремя: <code>{time}</code>",
        'news_header': "📅 <b>Экономический Календарь (USD)</b>\n\n",
        'no_news': "📅 <b>Экономический Календарь</b>\n\nВ ближайшие 24 часа важных новостей нет.",
        'settings_menu': "⚙️ <b>Настройки</b>\n\nВыберите язык или получите помощь:",
        'lang_uz': "🇺🇿 O'zbekcha",
        'lang_ru': "🇷🇺 Русский",
        'help_btn': "ℹ️ Помощь",
        'help_text': "ℹ️ <b>Центр Помощи</b>\n\nИнструкция по использованию бота:\n\n1. 📊 <b>Тарифы</b> - Покупка премиум подписки.\n2. 📈 <b>Рынок</b> - Текущая цена.\n3. 🗞 <b>Новости</b> - Важные экономические новости.\n4. ⚙️ <b>Настройки</b> - Изменение языка.\n\nЕсли есть вопросы, свяжитесь с админом: @musoqudratov",
        'lang_changed': "✅ Язык изменен: Русский",
        'payment_info': "💳 <b>Реквизиты Оплаты</b>\n\nТариф: <b>{duration}</b>\nЦена: <b>{price}</b>\n\nАдрес USDT (TRC20) для оплаты:\n<code>TYourActualUsdtAddressHere</code>\n\n⚠️ <b>Важно:</b> После оплаты отправьте скриншот @musoqudratov.",
        'sub_approved': "🎉 <b>Премиум Активирован!</b>\nДни: {days}\nИстекает: {date}\n\nКанал: <a href='{link}'>Вход</a>",
        'sub_rejected': "❌ Ваш запрос на оплату отклонен.",
        'cancel': "Отмена",
        'cancelled': "❌ Отменено.",
        'back_to_main': "Управляйте ботом с помощью кнопок ниже:",
        'manual_signal_start': "📝 <b>Создать Сигнал</b>\n\nВыберите тип сигнала:",
        'manual_signal_price': "✅ {type} выбран.\n\nТеперь введите <b>Цену входа</b> (например: 2030.50):",
        'manual_signal_sl': "✅ Цена: {price}\n\nТеперь введите <b>Stop Loss (SL)</b>:",
        'manual_signal_tp': "✅ SL: {sl}\n\nТеперь введите <b>Take Profit (TP)</b>:",
        'manual_signal_reason': "✅ TP: {tp}\n\nТеперь напишите <b>Причину</b> (например: Trendline Support):",
        'manual_signal_preview': "✅ Сигнал готов! Проверьте ниже:",
        'error_num': "⚠️ Пожалуйста, отправьте только число.",
        'error_type': "⚠️ Пожалуйста, выберите BUY или SELL."
    }
}
